export const $ = (selector, root = document) => root.querySelector(selector);
export const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

export function getElements() {
  return {
    modeButtons: $$(".mode-button"),
    dropZone: $("#drop-zone"),
    fileInput: $("#file-input"),
    folderInput: $("#folder-input"),
    zipInput: $("#zip-input"),
    selectFiles: $("#select-files"),
    selectFolder: $("#select-folder"),
    selectZip: $("#select-zip"),
    emptySelect: $("#empty-select"),
    clearAll: $("#clear-all"),
    mergeAll: $("#merge-all"),
    emptyState: $("#empty-state"),
    queueList: $("#queue-list"),
    fileCount: $("#file-count"),
    summaryCard: $("#summary-card"),
    summaryProgress: $("#summary-progress"),
    summaryTitle: $("#summary-title"),
    summaryDetail: $("#summary-detail"),
    summaryCount: $("#summary-count"),
    dockLabel: $("#dock-label"),
    dockDetail: $("#dock-detail"),
    processAll: $("#process-all"),
    processLabel: $("#process-label"),
    downloadAll: $("#download-all"),
    template: $("#queue-item-template"),
    previewModal: $("#preview-modal"),
    previewClose: $("#preview-close"),
    previewTitle: $("#preview-title"),
    previewTabs: $$(".preview-tab"),
    previewPanes: $$("[data-preview-pane]"),
    beforeCaption: $("#before-caption"),
    beforePreview: $("#before-preview"),
    afterLabel: $("#after-label"),
    afterTabLabel: $("#after-tab-label"),
    afterPreview: $("#after-preview"),
    previewFilename: $("#preview-filename"),
    previewMeta: $("#preview-meta"),
    previewDownload: $("#preview-download"),
    previewBackdrop: $("[data-close-preview]"),
    mergeModal: $("#merge-modal"),
    mergeClose: $("#merge-close"),
    mergeBackdrop: $("[data-close-merge]"),
    mergeDirectionButtons: $$(".merge-direction-button"),
    mergePreviewShell: $("#merge-preview-shell"),
    mergePreview: $("#merge-preview"),
    mergeLoading: $("#merge-loading"),
    mergeSummary: $("#merge-summary"),
    mergeMeta: $("#merge-meta"),
    mergeDownload: $("#merge-download"),
    mergeAdd: $("#merge-add"),
    mergeProcess: $("#merge-process"),
    mergeProcessLabel: $("#merge-process-label"),
    toast: $("#toast")
  };
}
